# Generated by Django 4.1.7 on 2023-05-01 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='id_wallet',
        ),
        migrations.AddField(
            model_name='wallet',
            name='categories',
            field=models.ManyToManyField(to='mainapp.category'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='id_user',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.AddField(
            model_name='finance',
            name='id_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.wallet'),
        ),
    ]
