# Generated by Django 4.1.7 on 2023-05-07 22:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finance',
            new_name='FinanceOperation',
        ),
        migrations.RenameField(
            model_name='financeoperation',
            old_name='name',
            new_name='title',
        ),
    ]
