# Generated by Django 4.1.9 on 2023-05-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_finance_financeoperation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeoperation',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='financeoperation',
            name='id_wallet',
        ),
        migrations.AddField(
            model_name='financeoperation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
        ),
        migrations.AddField(
            model_name='financeoperation',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.wallet'),
        ),
    ]
