# Generated by Django 4.1.7 on 2023-05-01 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_finance_remove_category_id_wallet_wallet_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
