# Generated by Django 4.1.7 on 2023-05-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_wallet_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='id_user',
        ),
    ]
