# Generated by Django 4.1.9 on 2023-05-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_financeoperation_expanseoperation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeoperation',
            name='category',
        ),
    ]
