# Generated by Django 4.0.5 on 2023-05-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_expanseoperation_id_user_incomeoperation_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_balance',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
    ]
