# Generated by Django 4.2.1 on 2023-06-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_expanseoperation_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expanseoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='incomeoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
