# Generated by Django 4.2.1 on 2023-06-13 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_expanseoperation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expanseoperation',
            name='operation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='incomeoperation',
            name='operation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
